package tn.iit.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import tn.iit.entity.User;
import tn.iit.repository.UserRepository;
import tn.iit.request.CreateUserRequest;
import tn.iit.response.UserResponse;
import tn.iit.service.UserService;
import org.springframework.web.bind.annotation.ResponseBody;
@RestController
@RequestMapping("/api/user")
public class UserController {
	
	@Autowired
	UserService userService;
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@PostMapping("/create")
	public UserResponse createUser (@RequestBody CreateUserRequest createUserRequest) {
		return userService.createUser(createUserRequest);
	}
	
	@GetMapping("getById/{id}")
	public UserResponse getById (@PathVariable long id) {
		return userService.getById(id);
	}
	
	 @GetMapping("/all")
	  public @ResponseBody Iterable<User> getAllUsers() {
	    return userService.getAllUsers();
	  }
	 
	 @PostMapping("/update/{id}")
		public UserResponse updateUser (@PathVariable long id,@RequestBody CreateUserRequest createUserRequest) {
			return userService.UpdateById(id, createUserRequest);
		}
	 
	 @PostMapping("/delete/{id}")
		public void deleteUser (@PathVariable long id) {
			userService.DeleteUser(id);
		}
}
